module.exports = {
    siteMetadata: {
        title: `Maxime Richard - zyhou`,
        description: `Maxime Richard, zyhou, full stack développeur sur Nancy`,
        keywords: `Maxime Richard, zyhou, Nancy, Web, full stack, React, Node`,
        author: `Maxime Richard`,
        pseudo: `zyhou`,
        siteUrl: `https://zyhou.github.io`,
        githubRepoUrl: `https://github.com/zyhou/zyhou`,
        linkedinUrl: `https://www.linkedin.com/in/maximerichard9/`,
        twitterName: `@choukmax`,
        twitterUrl: `https://twitter.com/choukmax`,
        instagramUrl: `https://www.instagram.com/choukmax/`,
    },
    plugins: [
        `gatsby-plugin-react-helmet`,
        `gatsby-plugin-sitemap`,
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `images`,
                path: `${__dirname}/src/images`,
            },
        },
        `gatsby-transformer-sharp`,
        `gatsby-plugin-sharp`,
        `gatsby-plugin-postcss`,
        {
            resolve: `gatsby-plugin-manifest`,
            options: {
                name: `Maxime Richard`,
                short_name: `Max`,
                description: `Maxime Richard, zyhou, full stack développeur sur Nancy`,
                start_url: `/`,
                homepage_url: `https://zyhou.github.io`,
                background_color: `#1a1a1a`,
                theme_color: `#1a1a1a`,
                display: `minimal-ui`,
                icon: `src/images/avatar.png`,
            },
        },
        `gatsby-plugin-offline`,
        `gatsby-plugin-robots-txt`,
    ],
};
